import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-black text-white antialiased font-sans ${geistSans.variable} ${geistMono.variable}`}
      >

        {children}
        <Toaster
          position="top-center" //  置中顯示
          toastOptions={{
            style: {
              background: "#1f1f1f",    // 背景黑
              color: "#ffa500",         // 文字橘
              fontWeight: 600,
              border: "1px solid #ffa500",
              borderRadius: "8px",
            },
          }} />  {/* 顯示 toast 容器 */}
      </body>
    </html>
  );
}


